rentsome/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from user import views
from product import views

urlpatterns = [
    path('',views.List,name = 'MainPage'),
    path('admin/', admin.site.urls),
    path('user/',include("user.urls")),
    path('product/',include("product.urls")),
    path('comment/',include("comment.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from user import views

app_name = "user"


urlpatterns = [
    path('login/',views.Login, name = 'login'),
    path('register/',views.Register, name = 'register'),
    path('logout/',views.Logout,name = "logout"),
    path('detail/<int:id>/',views.Detail,name="user_detail"),
    path('update/<int:id>/',views.Update,name="update"),
]

templates/navbar/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Ana Sayfa</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      {% if request.user.is_authenticated %}
      <li class="navbar-item" >
        <a class="nav-link" href="/product/myproducts/{{request.user.id}}" > Ürünlerim </a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="/product/rent_item">Ürün Kirala</a>
      </li>
    </ul>
{% endif %}

    <ul class = "navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
      <li class="nav-item ">
        <a class="nav-link" href="/user/detail/{{request.user.id}}">{{request.user}}</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="/user/logout">Çıkış Yap</a>
      </li>
      {% else %}
      <li class="nav-item ">
        <a class="nav-link" href="{% url 'user:login'  %}">Giriş Yap</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="/user/register">Kayıt Ol</a>
      </li>
      {% endif %}
    </ul>


  </div>
</nav>