comment/urls.py
from django.contrib import admin
from django.urls import path
from comment import views

app_name = "comment"

urlpatterns = [
    path("comments/<int:id>",views.ProductComment,name="comments"),
    path("nested_comment/<int:id>",views.NestedComment,name="nested_comment"),
]

product/urls.py
from django.contrib import admin
from django.urls import path
from product import views

app_name = "product"

urlpatterns = [
    path("detail/<int:id>",views.detail,name = 'detail'),
    path("myproducts/<int:id>",views.my_products,name='myproducts'),
    path("rent_item/",views.rent_items,name='rent_item'),
    path("rent/<int:id>",views.rental,name='rent'),

]

rentsome/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from user import views
from product import views

urlpatterns = [
    path('',views.List,name = 'MainPage'),
    path('admin/', admin.site.urls),
    path('user/',include("user.urls")),
    path('product/',include("product.urls")),
    path('comment/',include("comment.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from user import views

app_name = "user"


urlpatterns = [
    path('login/',views.Login, name = 'login'),
    path('register/',views.Register, name = 'register'),
    path('logout/',views.Logout,name = "logout"),
    path('detail/<int:id>/',views.Detail,name="user_detail"),
    path('update/<int:id>/',views.Update,name="update"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>RentSome</title>
</head>
<body>

        <div style = "margin-bottom:150px;" class = "container">

            {% if messages %}

                    {% for message in messages %}
                    {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                    {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>

                    {% endif %}


                    {% endfor %}

            {% endif %}


            {% include "navbar/navbar.html" %}

            <div style = "margin-top:20px;" class = "container">


                {% load staticfiles %}


            {% block body %}



            {% endblock body %}

        </div>

    </body>
</html>

templates/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block body %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş Yap</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}

            {{form|crispy}}

            <br>
            <button type = "submit" class = "btn btn-primary">Giriş Yap</button>
        </form>
    </div>
  </div>


{% endblock body %}

templates/my_product.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block body %}

<h3>Kiradaki Ürünler</h3>
{% if hired %}
    {% for products in hired %}

<!-- Page Content -->
    <!-- Page Content -->
    <div class="container">
      <!-- Page Heading -->
      <h4 class="my-4"> <!-- {{product.name}} -->
        <small></small>
      </h4>
      <!-- Project One -->
      <div class="row">
        <div class="col-md-7">
          <a href="{% url 'product:detail' products.id %}">
          {% if products.product_image %}
          <img  class="img-fluid rounded" src="{{products.product_image.url}}" alt="">
        {% else %}
          <img class="img-fluid rounded mb-3 mb-md-0" src="http://placehold.it/700x300" alt="">
            {% endif %}
          </a>
        </div>
        <div class="col-md-5">
          <h4 class="card-title">
            <a href="{% url 'product:detail' products.id %}">{{product.name}}</a>
          </h4>
          <p class="card-text">

        Sahibi : {{products.owner}} <br>
        Ürün Adı : {{products.name}}<br>

        Açıklama : {{products.description}} <br>
        Fiyat : {{products.price}} $<br>
        Kiralayan : {{products.hirer}}<br>
              Kiralık Bitiş Tarihi= {{products.hire_end_date}} <br>
            <a class="btn btn-danger" href="{% url 'product:detail' products.id %}">Kirada</a>
        </div>
      </div>
    </div>
      <!-- /.row -->
      <hr>
  {% endfor %}

<hr>
{% else %}
<p>Kirada Ürününüz Bulunmamaktadir</p>
{% endif %}

<hr>

<h3>Kiralanmayi Bekleyen Ürünler</h3>
{% if wait_hire %}
        {% for products in wait_hire %}

<!-- Page Content -->
    <!-- Page Content -->
    <div class="container">
      <!-- Page Heading -->
      <h4 class="my-4"> <!-- {{product.name}} -->
        <small></small>
      </h4>
      <!-- Project One -->
      <div class="row">
        <div class="col-md-7">
          <a href="{% url 'product:detail' products.id %}">
          {% if products.product_image %}
          <img  class="img-fluid rounded" src="{{products.product_image.url}}" alt="">
        {% else %}
          <img class="img-fluid rounded mb-3 mb-md-0" src="http://placehold.it/700x300" alt="">
            {% endif %}
          </a>
        </div>
        <div class="col-md-5">
          <h4 class="card-title">
            <a href="{% url 'product:detail' products.id %}">{{product.name}}</a>
          </h4>
          <p class="card-text">

        Sahibi : {{products.owner}} <br>
        Ürün Adı : {{products.name}}<br>
        Eklenme Tarihi : {{products.create_date}}<br>
        Açıklama : {{products.description}} <br>
        Fiyat : {{products.price}} $<br>
    <hr>
            <a class="btn btn-primary" href="{% url 'product:detail' products.id %}">Detay</a>
        </div>
      </div>
    </div>
      <!-- /.row -->
    <hr>
  {% endfor %}

<hr>

{% else %}
<p>Kiralanmayı Bekleyen Ürününüz Bulunmamaktadır...</p>
{% endif %}


<hr>

<h3>Kiraladiginiz Ürünler</h3>
{% if hired_from_me %}
    {% for products in hired_from_me %}

<!-- Page Content -->
    <!-- Page Content -->
    <div class="container">
      <!-- Page Heading -->
      <h4 class="my-4"> <!-- {{product.name}} -->
        <small></small>
      </h4>
      <!-- Project One -->
      <div class="row">
        <div class="col-md-7">
          <a href="{% url 'product:detail' products.id %}">
          {% if products.product_image %}
          <img  class="img-fluid rounded" src="{{products.product_image.url}}" alt="">
        {% else %}
          <img class="img-fluid rounded mb-3 mb-md-0" src="http://placehold.it/700x300" alt="">
            {% endif %}
          </a>
        </div>
        <div class="col-md-5">
          <h4 class="card-title">
            <a href="{% url 'product:detail' products.id %}">{{product.name}}</a>
          </h4>
          <p class="card-text">

        Sahibi : {{products.owner}} <br>
        Ürün Adı : {{products.name}}<br>

        Açıklama : {{products.description}} <br>
        Fiyat : {{products.price}} $<br>
        Kiralayan : {{products.hirer}}<br>
              Kiralık Bitiş Tarihi= {{products.hire_end_date}} <br>
            <a class="btn btn-danger" href="{% url 'product:detail' products.id %}">Kirada</a>
        </p>
        </div>
      </div>
    </div>
      <!-- /.row -->
<hr>
{% endfor %}
<hr>
{% else %}
    <p>Kiraladiginiz Ürün Bulunmamaktadir</p>
{% endif %}
{% endblock body %}

templates/product_detail.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block body %}


<div class="container">
  <!-- Page Heading -->
    <h3 class="my-4">{{product.name}} Detay
  </h3>
        <div class="col-lg-6 mb-4">
      <div class="card h-100">
        {% if product.product_image %}
          <img  class="img-fluid rounded" src="{{product.product_image.url}}" alt="">
        {% else %}
          <img class="card-img-top" src="http://placehold.it/700x400" alt="">
          {% endif %}
        <div class="card-body">
          <h4 class="card-title">
              {{product.name}}
          </h4>
            <p class="card-text"> Açıklama : {{product.description}}</p>
            <p class="card-date" > Oluşturulma Tarihi : {{product.create_date}} </p>
            <p class="card-text"> Sahibi : {{product.owner}}</p>

            {% if product.is_available%}
            <form action="{% url 'product:rent' product.id %}" method="Post">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" name="id" value="{{products.id}}">Kirala!</button>
            </form>

        {% else %}
            Kiralık Bitiş Tarihi= {{product.hire_end_date}} <br>
            Kiralayan = {{product.hirer}}
        {% endif %}
        </div>
      </div>
    </div>
</div>

    <h3>Yorumlar</h3> <hr>

{% if comment_list %}
    {% for comment in comment_list  %}
        <div class="media mb-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
              <h5 class="mt-0">{{comment.sender}}</h5>
              {{comment.comment}} <br>
              {{comment.date}}

          </div>
        </div>
      {% endfor %}


      {% else %}
      <div class ="alert alert-primary">
        Bu makaleye herhangi bir yorum yazılmamış,ilk yorum yapan siz olun!
      </div>
      {% endif %}

      <div class="card my-4">
          <h5 class="card-header">Yorum Ekle:</h5>
          <div class="card-body">
            <form method = "post" action = "{% url 'comment:comments' product.id %}">
              {% csrf_token %}
              <div class="form-group">
                  <label >Yorum</label>
                <textarea name = "comment" class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Ekle</button>
            </form>
          </div>
        </div>
        </div>

      </div>


{% endblock body %}

templates/product_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block body %}


<!-- Page Content -->

  {% for product in products %}
    <!-- Page Content -->
    <div class="container">

      <!-- Page Heading -->
      <h4 class="my-4"> <!-- {{product.name}} -->
        <small></small>
      </h4>
      <!-- Project One -->
      <div class="row">
        <div class="col-md-7">
          <a href="{% url 'product:detail' product.id %}">
          {% if product.product_image %}
          <img  class="img-fluid rounded" src="{{product.product_image.url}}" alt="">
        {% else %}
          <img class="img-fluid rounded mb-3 mb-md-0" src="http://placehold.it/700x300" alt="">
            {% endif %}
          </a>
        </div>
        <div class="col-md-5">
          <h4 class="card-title">
            <a href="{% url 'product:detail' product.id %}">{{product.name}}</a>
          </h4>
          <p class="card-text">
            Açıklama : {{product.description}}</p>
            Eklenme Tarihi : {{product.create_date}}</p>
            price : {{product.price}} $<br>

        {% if product.is_available%}
          <a class="btn btn-primary" href="{% url 'product:detail' product.id %}">İncele</a>
        {% else %}
            Kiralık Bitiş Tarihi= {{product.hire_end_date}} <br>
            Kiralayan = {{product.hirer}}<br>
            <a class="btn btn-danger" href="{% url 'product:detail' product.id %}">Kirada</a>
        {% endif %}
        </div>
      </div>
    </div>
      <!-- /.row -->
      <hr>
  {% endfor %}

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="/static/CSS/heads.css" rel="stylesheet">

<div class="pagination">

  {% if products.has_previous %}
    <a class="pagination-action" href="?page=1">
     <i class="fa fa-angle-double-left" aria-hidden="true"></i>
    </a>
    <a class="pagination-action" href="?page={{ products.previous_page_number }}">
      <i class="fa fa-angle-left" aria-hidden="true"></i>
    </a>
  {% endif %}

  {% for num in products.paginator.page_range %}

    {% if products.number == num %}
    <span class="pagination-number pagination-current">{{ num }}</span>
    {% elif num > products.number|add:'-3' and num < products.number|add:'3' %}
    <a class="pagination-number" href="?page={{ num }}">{{ num }}</a>
    {% endif %}

  {% endfor %}

  {% if products.has_next %}
    <a class="pagination-action" href="?page={{ products.next_page_number }}">
      <i class="fa fa-angle-right" aria-hidden="true"></i>
    </a>
    <a class="pagination-action" href="?page={{ products.paginator.num_pages }}">
      <i class="fa fa-angle-double-right" aria-hidden="true"></i>
    </a>
  {% endif %}

</div>

{% endblock body %}

templates/profile_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block body %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Profili Güncelle</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Güncelle</button>
        </form>
    </div>
  </div>



{% endblock body %}

templates/register.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block body %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt Ol</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}

            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-primary">Giriş Yap</button>
        </form>
    </div>
  </div>



{% endblock body %}

templates/rent_item.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block body %}


<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Ürün Kirala</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}

            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Kirala</button>
        </form>
    </div>
  </div>


{% endblock body %}

templates/user_detail.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block body %}


        {% if user.profile_picture %}
        <img class="img-fluid rounded" src="{{user.profile_picture.url}}" alt="">
        {% else %}
            <h3> Profil Resmi Bulunmamaktadır... </h3>
        {% endif %}

    Kullanıcı Adı : {{user.username}}<br>
    Ad : {{user.first_name}}<br>
    Soyad : {{user.last_name}}<br>
    e-mail : {{user.email}}<br>
    Konum : {{user.location}}<br>
    Para : {{user.money}}<br>


    <td><a href="{% url 'user:update' request.user.id %}" class = "btn btn-danger">Güncelle</a></td>

{% endblock body %}